# Generated by Django 3.1.2 on 2020-10-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20201027_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='like',
            new_name='likes',
        ),
    ]
